version: '3.1'
services:
  parser:
    image: alphabotsystem/alpha-parser
    build:
      context: ./
      dockerfile: ./services/parser/build/dockerfile
    volumes:
     - ./services/parser:/usr/src/parser
     - ./libraries:/usr/src/parser/libraries
    ports:
     - "6900:6900"
    secrets:
     - source: alpha-service-keys
       target: alpha-service/key
     - source: google-cloud-auth
       target: google-cloud-auth/key
    depends_on:
     - serum-server

  database:
    image: alphabotsystem/alpha-database
    build:
      context: ./
      dockerfile: ./services/database/build/dockerfile
    volumes:
     - ./services/database:/usr/src/database
     - ./libraries:/usr/src/database/libraries
    ports:
     - "6901:6900"
    secrets:
     - source: alpha-service-keys
       target: alpha-service/key
     - source: google-cloud-auth
       target: google-cloud-auth/key

  image-server:
    image: alphabotsystem/alpha-image-server
    build:
      context: ./
      dockerfile: ./services/images/build/dockerfile
    volumes:
     - ./services/images:/usr/src/image-server
     - ./libraries:/usr/src/image-server/libraries
    ports:
     - "6902:6900"
    secrets:
     - source: alpha-service-keys
       target: alpha-service/key
     - source: google-cloud-auth
       target: google-cloud-auth/key
    depends_on:
     - parser

  quote-server:
    image: alphabotsystem/alpha-quote-server
    build:
      context: ./
      dockerfile: ./services/quotes/build/dockerfile
    volumes:
     - ./services/quotes:/usr/src/quote-server
     - ./libraries:/usr/src/quote-server/libraries
    ports:
     - "6903:6900"
    secrets:
     - source: alpha-service-keys
       target: alpha-service/key
     - source: google-cloud-auth
       target: google-cloud-auth/key
    depends_on:
     - parser
     - serum-server

  serum-server:
    image: alphabotsystem/alpha-serum-server
    build:
      context: ./
      dockerfile: ./services/serum/build/dockerfile
    volumes:
     - ./services/serum:/usr/src/serum-server
    ports:
     - "6904:6900"
    secrets:
     - source: alpha-service-keys
       target: alpha-service/key
     - source: google-cloud-auth
       target: google-cloud-auth/key

  detail-server:
    image: alphabotsystem/alpha-detail-server
    build:
      context: ./
      dockerfile: ./services/details/build/dockerfile
    volumes:
     - ./services/details:/usr/src/detail-server
     - ./libraries:/usr/src/detail-server/libraries
    ports:
     - "6905:6900"
    secrets:
     - source: alpha-service-keys
       target: alpha-service/key
     - source: google-cloud-auth
       target: google-cloud-auth/key
    depends_on:
     - parser

  candle-server:
    image: alphabotsystem/alpha-candle-server
    build:
      context: ./
      dockerfile: ./services/candles/build/dockerfile
    volumes:
     - ./services/candles:/usr/src/candle-server
     - ./libraries:/usr/src/candle-server/libraries
    ports:
     - "6906:6900"
    secrets:
     - source: alpha-service-keys
       target: alpha-service/key
     - source: google-cloud-auth
       target: google-cloud-auth/key
    depends_on:
     - parser

  ichibot-server:
    image: alphabotsystem/alpha-ichibot-server
    build:
      context: ./
      dockerfile: ./services/ichibot/build/dockerfile
    volumes:
     - ./services/ichibot:/usr/src/ichibot-server
    ports:
     - "6907:6900"
    secrets:
     - source: alpha-service-keys
       target: alpha-service/key
     - source: ichibot-credentials
       target: ichibot-credentials/key
     - source: google-cloud-auth
       target: google-cloud-auth/key

  ichibot-relay-server:
    image: alphabotsystem/alpha-ichibot-relay-server
    build:
      context: ./
      dockerfile: ./services/ichibotrelay/build/dockerfile
    volumes:
     - ./services/ichibotrelay:/usr/src/ichibotrelay
     - ./libraries:/usr/src/ichibotrelay/libraries
    ports:
     - "6908:6900"
    secrets:
     - source: alpha-service-keys
       target: alpha-service/key
     - source: google-cloud-auth
       target: google-cloud-auth/key
    depends_on:
     - parser

  alerts-server:
    image: alphabotsystem/alpha-alerts-server
    build:
      context: ./
      dockerfile: ./services/alerts/build/dockerfile
    volumes:
     - ./services/alerts:/usr/src/alerts-server
     - ./libraries:/usr/src/alerts-server/libraries
    ports:
     - "6909:6900"
    secrets:
     - source: alpha-service-keys
       target: alpha-service/key
     - source: google-cloud-auth
       target: google-cloud-auth/key
    depends_on:
     - parser
     - database
     - candle-server

  paper-trader-server:
    image: alphabotsystem/alpha-paper-trader-server
    build:
      context: ./
      dockerfile: ./services/papertrader/build/dockerfile
    volumes:
     - ./services/papertrader:/usr/src/paper-trader-server
     - ./libraries:/usr/src/paper-server/libraries
    ports:
     - "6910:6900"
    secrets:
     - source: alpha-service-keys
       target: alpha-service/key
     - source: google-cloud-auth
       target: google-cloud-auth/key
    depends_on:
     - parser
     - database
     - candle-server

  discord-bot:
    image: alphabotsystem/alpha-discord-bot
    build:
      context: ./
      dockerfile: ./bots/discord/build/dockerfile
    volumes:
     - ./bots/discord:/usr/src/discord-bot
     - ./libraries:/usr/src/discord-bot/libraries
    ports:
     - "6920:6900"
    secrets:
     - source: alpha-service-keys
       target: alpha-service/key
     - source: google-cloud-auth
       target: google-cloud-auth/key
    depends_on:
     - parser
     - database
     - image-server
     - quote-server
     - detail-server
     - candle-server
     - ichibot-server

  satellites:
    image: alphabotsystem/alpha-satellites
    build:
      context: ./
      dockerfile: ./bots/satellites/build/dockerfile
    volumes:
     - ./bots/satellites:/usr/src/satellites
     - ./libraries:/usr/src/satellites/libraries
    ports:
     - "6921:6900"
    secrets:
     - source: alpha-service-keys
       target: alpha-service/key
     - source: alpha-satellite-keys
       target: alpha-satellites/key
     - source: google-cloud-auth
       target: google-cloud-auth/key
    depends_on:
     - parser
     - database
     - quote-server

#   twitter-bot:
#     image: alphabotsystem/alpha-twitter-bot
#     build:
#       context: ./
#       dockerfile: ./bots/twitter/build/dockerfile
#     volumes:
#      - ./bots/twitter:/usr/src/twitter-bot
#      - ./libraries:/usr/src/twitter-bot/libraries
#     ports:
#      - "6922:6900"
#     secrets:
#      - source: alpha-service-keys
#        target: alpha-service/key
#      - source: google-cloud-auth
#        target: google-cloud-auth/key
#     depends_on:
#      - parser
#      - database
#      - image-server
#      - quote-server
#      - detail-server

  discord-manager:
    image: alphabotsystem/alpha-discord-manager
    build:
      context: ./
      dockerfile: ./bots/manager/build/dockerfile
    volumes:
     - ./bots/manager:/usr/src/discord-manager
     - ./libraries:/usr/src/discord-manager/libraries
    secrets:
     - source: alpha-service-keys
       target: alpha-service/key
     - source: google-cloud-auth
       target: google-cloud-auth/key
    depends_on:
     - database


secrets:
  alpha-service-keys:
    file: ./keys/credentials
  ichibot-credentials:
    file: ./keys/ichibot_credentials
  alpha-satellite-keys:
    file: ./keys/satellites
  google-cloud-auth:
    file: ./keys/gcloud_credentials.json